const colors = [
  "Black",
  "White",
  "Gray",
  "Navy Blue",
  "Olive Green",
  "Camel",
  "Rust",
  "Red",
  "Royal Blue",
  "Emerald Green",
  "Beige",
  "Burgundy",
  "Blush Pink",
  "Mustard Yellow",
  "Taupe",
  "Mauve",
  "Lavender",
  "Teal",
  "Sapphire Blue",
  "Coral",
  "Peach",
  "Silver",
  "Gold",
  "Champagne",
  "Ivory",
  "Plum",
  "Chocolate Brown",
  "Sky Blue",
  "Forest Green",
  "Turquoise",
  "Charcoal",
  "Lilac",
  "Mint Green",
  "Fuchsia",
  "Burnt Orange",
  "Amethyst",
  "Crimson",
  "Indigo",
  "Pearl White",
  "Rose Gold",
  "Steel Blue",
  "Pale Yellow",
  "Deep Purple",
  "Copper",
  "Salmon Pink",
  "Oxblood Red",
  "Pastel Blue",
  "Sunset Orange",
];

const itemsTypes = [
  "Saree",
  "Lehenga Choli",
  "Anarkali Suit",
  "Maxi Dress",
  "Cocktail Dress",
  "Salwar Kameez",
  "Patiala Suit",
  "Churidar Suit",
  "Wrap Dress",
  "Shift Dress",
  "Sharara",
  "Gharara",
  "Palazzo Suit",
  "Punjabi Suit",
  "A-line Dress",
  "Ball Gown",
  "Peplum Dress",
  "Bodycon Dress",
  "Midi Dress",
  "Mini Dress",
  "Jumpsuit",
  "Romper",
  "Tunic Dress",
  "Sheath Dress",
  "Mermaid Gown",
  "Off-shoulder Gown",
  "Halter Gown",
  "Empire Waist Gown",
  "Tea-length Gown",
  "Fit and Flare Gown",
  "Bardot Gown",
  "High-Low Gown",
  "Slip Gown",
  "T-shirt Gown",
  "Denim Gown",
  "Lace Gown",
  "Sequin Gown",
  "Velvet Gown",
  "Silk Gown",
  "Chiffon Gown",
  "Tulle Gown",
  "Floral Gown",
  "Printed Gown",
  "Geometric Gown",
  "Polka Dot Gown",
  "Ruffled Gown",
  "Embroidered Gown",
  "Shirtwaist Dress",
  "Kaftan Dress",
  "Kimono Dress",
  "Pinafore Dress",
  "Pleated Dress",
  "Tiered Dress",
  "Belted Dress",
  "Peasant Dress",
  "Gingham Dress",
];

const inspirations = [
  "Indian",
  "Egyptian",
  "Arabic",
  "Japanese",
  "Chinese",
  "Korean",
  "Greek",
  "Roman",
  "Italian",
  "French",
  "Spanish",
  "British",
  "American",
  "African",
  "Scandinavian",
];

export { inspirations, colors, itemsTypes };
